languages:
  Ruby: true
  JavaScript: true
  PHP: true
  Python: true
exclude_paths:
- "app/assets/javascripts/bootstrap.js"
- "app/assets/javascripts/facebox.js"
- "app/assets/javascripts/jBox.js"
- "app/assets/javascripts/jquery.flexslider.js"
