development:
  adapter: postgresql
  encoding: unicode
  database: ddl
  pool: 5
  username: truenito
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ddl
  pool: 5
  username: truenito
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: ddl
  pool: 5
  username: truenito
  password:
